version: 0.2

phases:
  pre_build:
    commands:
      - pwd
      - find .
      - printf "CODEBUILD_SRC_DIR_source1=%s\n" "$CODEBUILD_SRC_DIR_source1"
      - printf "CODEBUILD_SRC_DIR_source=%s\n" "$CODEBUILD_SRC_DIR_source"
  post_build:
    commands:
      - rm -f buildspec-frontend-zip-deploy.yml
      - aws s3 sync . s3://xrx-498317514113-frontend-static-1/ --exclude '*' --include 'index.html' --cache-control 'max-age=5'
      - aws s3 sync . s3://xrx-498317514113-frontend-static-1/ --include '*' --exclude 'index.html' --cache-control 'max-age=11'
