version: 0.2

phases:
  pre_build:
    commands:
      - pwd
      - find .
      - printf "CODEBUILD_SRC_DIR_source1=%s\n" "$CODEBUILD_SRC_DIR_source1"
      - printf "CODEBUILD_SRC_DIR_source=%s\n" "$CODEBUILD_SRC_DIR_source"
  post_build:
    commands:
      - aws s3 cp --cache-control max-age=5 index.html s3://xrx-498317514113-frontend-static-1/
      - aws s3 cp --cache-control max-age=11 script.js style.css s3://xrx-498317514113-frontend-static-1/
