version: 0.2

phases:
  pre_build:
    commands:
      - aws sts get-caller-identity
artifacts:
  files:
    - 'index.html'
    - 'script.js'
    - 'style.css'
    - 'buildspec-frontend-zip-deploy.yml'
  base-directory: 'frontend'
  name: frontend-$(date +%Y-%m-%dT%H:%M:%S.%N%z) 
