version: 0.2

phases:
  pre_build:
    commands:
      - aws sts get-caller-identity
  build:
    commands:
      - printf "FIXME build backend Docker image"
  post_build:
    commands:
      - printf "FIXME push backend Docker image"
