version: 0.2

phases:
  pre_build:
    commands:
      - aws sts get-caller-identity
      - echo Logging in to Amazon ECR...
      - aws --version
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
      - REPOSITORY_URI=498317514113.dkr.ecr.eu-west-1.amazonaws.com/mypi-backend
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - cd backend/
      - sed -i "s,__COMMIT__,${CODEBUILD_RESOLVED_SOURCE_VERSION},g" local.env
      - docker build -t $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo Writing image definitions file...
      - printf '[{"name":"mypi-container-1","imageUri":"%s:%s"}]' "$REPOSITORY_URI" "$IMAGE_TAG" | tee imagedefinitions.json
artifacts:
  files:
    - 'imagedefinitions.json'
  base-directory: 'backend'
